- hosts: all
  tasks: 
  - name: install the latest version of Apache
    yum:
      name:
        - httpd
        - wget
        - tree
      state: latest
  - name: install the latest version of GIT
    yum:
      name: git
      state: latest  
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started
  - name: Enable service httpd, and not touch the state
    service:
      name: httpd
      enabled: yes
  - name: Stop service httpd, if started
    service:
      name: httpd
      state: stopped


  - name: REMOVE the latest version of GIT
    yum:
      name: git
      state: absent  